/** Ceres Edge — dark theme tokens ported from
 *  wireframes/smart_farm_dashboard/code.html (the rendered dark wireframe). */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        primary: '#54e98a',
        'on-primary': '#003919',
        'primary-container': '#2ecc71',
        'on-primary-container': '#005027',
        'primary-fixed': '#6bfe9c',
        'primary-fixed-dim': '#4ae183',
        'on-primary-fixed': '#00210c',
        'on-primary-fixed-variant': '#005228',
        secondary: '#92ccff',
        'on-secondary': '#003351',
        'secondary-container': '#3398db',
        'on-secondary-container': '#002c47',
        'secondary-fixed': '#cce5ff',
        'secondary-fixed-dim': '#92ccff',
        'on-secondary-fixed': '#001d31',
        'on-secondary-fixed-variant': '#004b73',
        tertiary: '#f7c919',
        'on-tertiary': '#3c2f00',
        'tertiary-container': '#d7ae00',
        'on-tertiary-container': '#544300',
        'tertiary-fixed': '#ffe084',
        'tertiary-fixed-dim': '#eec209',
        'on-tertiary-fixed': '#231b00',
        'on-tertiary-fixed-variant': '#574500',
        error: '#ffb4ab',
        'on-error': '#690005',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',
        background: '#111316',
        'on-background': '#e2e2e6',
        surface: '#111316',
        'surface-dim': '#111316',
        'surface-bright': '#37393d',
        'surface-container-lowest': '#0c0e11',
        'surface-container-low': '#1a1c1f',
        'surface-container': '#1e2023',
        'surface-container-high': '#282a2d',
        'surface-container-highest': '#333538',
        'on-surface': '#e2e2e6',
        'on-surface-variant': '#bbcbbb',
        'surface-variant': '#333538',
        outline: '#869486',
        'outline-variant': '#3d4a3e',
        'inverse-surface': '#e2e2e6',
        'inverse-on-surface': '#2f3034',
        'inverse-primary': '#006d37',
        'surface-tint': '#4ae183',
      },
      fontFamily: {
        // 'Noto Sans Thai' is the trailing fallback so Thai glyphs render there
        // per-glyph while Latin stays in Hanken Grotesk / JetBrains Mono.
        'display-lg': ['Hanken Grotesk', 'Noto Sans Thai', 'system-ui', 'sans-serif'],
        'headline-md': ['Hanken Grotesk', 'Noto Sans Thai', 'system-ui', 'sans-serif'],
        'headline-sm': ['Hanken Grotesk', 'Noto Sans Thai', 'system-ui', 'sans-serif'],
        'body-md': ['Hanken Grotesk', 'Noto Sans Thai', 'system-ui', 'sans-serif'],
        'data-mono': ['JetBrains Mono', 'Noto Sans Thai', 'ui-monospace', 'monospace'],
        'label-caps': ['JetBrains Mono', 'Noto Sans Thai', 'ui-monospace', 'monospace'],
      },
      fontSize: {
        // Built-in scale bumped up for older users (xs 12->13, sm 14->15).
        xs: ['13px', { lineHeight: '18px' }],
        sm: ['15px', { lineHeight: '22px' }],
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'headline-sm': ['18px', { lineHeight: '24px', fontWeight: '600' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        // Bumped for readability (many users are older): data-mono 14->15,
        // label-caps 11->13. label-caps is the ubiquitous small-caps label (73+
        // uses), so this one change lifts most of the small text at once.
        'data-mono': ['15px', { lineHeight: '22px', letterSpacing: '0.02em', fontWeight: '500' }],
        'label-caps': ['13px', { lineHeight: '18px', letterSpacing: '0.06em', fontWeight: '700' }],
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '9999px',
      },
      spacing: {
        unit: '4px',
        gutter: '16px',
        'margin-mobile': '16px',
        'margin-desktop': '32px',
      },
      maxWidth: {
        'container-max': '1440px',
      },
    },
  },
  plugins: [],
};
