services:
  l4t-pytorch:
    image: nvcr.io/nvidia/pytorch:25.08-py3
    container_name: l4t-pytorch-container
    network_mode: host
    runtime: nvidia
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    stdin_open: true # Equivalent to -i
    tty: true        # Equivalent to -t
    #command: jupyter lab --ip=0.0.0.0 --port=8888 --allow-root --NotebookApp.token='' --NotebookApp.password=''
